// Auto-generated by: supabase gen types typescript --project-id <project-id> > src/types/database.types.ts
// Run this command after setting up your Supabase project to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be generated here
    }
    Views: {
      // Views will be generated here
    }
    Functions: {
      // Functions will be generated here
    }
    Enums: {
      // Enums will be generated here
    }
  }
}
