// Auto-generated by: supabase gen types typescript --project-id <project-id> > src/types/database.types.ts
// Run this command after setting up your Supabase project to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          nickname: string | null
          status: 'pending' | 'approved' | 'rejected'
          created_at: string | null
        }
        Insert: {
          id: string
          email?: string | null
          nickname?: string | null
          status?: 'pending' | 'approved' | 'rejected'
          created_at?: string | null
        }
        Update: {
          id?: string
          email?: string | null
          nickname?: string | null
          status?: 'pending' | 'approved' | 'rejected'
          created_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
